project:
  type: website
  output-dir: docs

website:
  title: "ethan skuches"
  navbar:
    right:
      - href: index.qmd
        text: about
      - Current & Past Projects.qmd
      - presentations.qmd
      - restoring_resiliency.qmd
      - href: photos.qmd
        text: photo gallery
      - blog.qmd
      - Knitting.qmd

format:
  html:
    theme: litera
    css: styles.scss
    mainfont: Inter
    toc: true
    page-layout: full
    lightbox: true

  